languageCode = 'en-us'
baseURL = "https://gmail-to-mb.sandernotenbaert.com"
title = "Moneybird Gmail Add-on"
disableKinds = ["taxonomy", "taxonomyTerm", "section", "sitemap", "RSS"]  # Simplifies the structure
